### ISSUE TITLE
KeyError: 31

### ISSUE THREAD

**Issue by SegzGitHub** [zzzeek/nbt2yaml#1]
I am a complete novice with coding and I know nothing about python so pardon if this is a bit stupid. I am trying to run nbt2yaml in my Ubuntu terminal. Here is what I get:

`sega@CerberusBox:/mnt/e/documents/Coding/nbt$ nbt2yaml -n level.dat
Traceback (most recent call last):
  File "/home/sega/.local/bin/nbt2yaml", line 8, in <module>
    sys.exit(nbt2yaml())
  File "/home/sega/.local/lib/python3.8/site-packages/nbt2yaml/main.py", line 96, in nbt2yaml
    struct = parse_nbt(input_, gzipped=not options.no_gzip)
  File "/home/sega/.local/lib/python3.8/site-packages/nbt2yaml/parse.py", line 180, in parse_nbt
    type_ = Tag.from_stream(stream)
  File "/home/sega/.local/lib/python3.8/site-packages/nbt2yaml/parse.py", line 22, in from_stream
    return cls._tags[struct.unpack(">b", stream.read(1))[0]]
KeyError: 31`

Not sure if it is a bug or if I did the install wrong or what. Any help would be appreciated.

**Comment by zzzeek** [comment]
it's a bug.  can you send me your level.dat , or one that shows the problem? thanks.

**Comment by SegzGitHub** [comment]
Uploaded different [files](https://drive.google.com/drive/folders/15LjGKGNnd5MTk-RxNhZvbOCRFZxWWTh9?usp=sharing) to google drive. level.dat, spawnerTest.nbt, and spawnerTest.schematic are from a custom modpack. otherlevel.dat is from a 1.16 instance.

**Comment by zzzeek** [comment]
your level.dat unpacks fine it looks like you are using the "-n" flag when you shouldn't be.  this file is gzipped.

**Comment by zzzeek** [comment]
```
$ nbt2yaml ~/Downloads/level.dat 
? ''
: - Data:
    - WanderingTraderSpawnChance: 25
    - BorderCenterZ: !double "0.0"
    - Difficulty: !byte "2"
    - BorderSizeLerpTime: !long "0"
    - raining: !byte "0"
    - Time: !long "109"
    - GameType: 0
    - ServerBrands: !list_string
      - vanilla
    - BorderCenterX: !double "0.0"
    - BorderDamagePerBlock: !double "0.2"
    - BorderWarningBlocks: !double "5.0"
    - WorldGenSettings:
      - bonus_chest: !byte "0"
      - seed: !long "6152230750795010955"
      - generate_features: !byte "1"
      - dimensions:
        - minecraft:overworld:
          - generator:
            - settings: minecraft:overworld
            - seed: !long "6152230750795010955"
            - biome_source:
              - seed: !long "6152230750795010955"
              - large_biomes: !byte "0"
              - type: minecraft:vanilla_layered
            - type: minecraft:noise
          - type: minecraft:overworld
        - minecraft:the_nether:
          - generator:
            - settings: minecraft:nether
            - seed: !long "6152230750795010955"
            - biome_source:
              - seed: !long "6152230750795010955"
              - preset: minecraft:nether
              - type: minecraft:multi_noise
            - type: minecraft:noise
          - type: minecraft:the_nether
        - minecraft:the_end:
          - generator:
            - settings: minecraft:end
            - seed: !long "6152230750795010955"
            - biome_source:
              - seed: !long "6152230750795010955"
              - type: minecraft:the_end
            - type: minecraft:noise
          - type: minecraft:the_end
    - DragonFight:
      - Gateways: !list_int
        - 2
        - 6
        - 12
        - 17
        - 19
        - 15
        - 8
        - 10
        - 1
        - 11
        - 0
        - 18
        - 13
        - 3
        - 16
        - 5
        - 4
        - 7
        - 9
        - 14
      - DragonKilled: !byte "1"
      - PreviouslyKilled: !byte "1"
    - BorderSizeLerpTarget: !double "60000000.0"
    - Version:
      - Snapshot: !byte "0"
      - Id: 2586
      - Name: 1.16.5
    - DayTime: !long "109"
    - initialized: !byte "1"
    - WasModded: !byte "0"
    - allowCommands: !byte "0"
    - WanderingTraderSpawnDelay: 24000
    - CustomBossEvents: []
    - GameRules:
      - doFireTick: 'true'
      - maxCommandChainLength: '65536'
      - fireDamage: 'true'
      - reducedDebugInfo: 'false'
      - disableElytraMovementCheck: 'false'
      - announceAdvancements: 'true'
      - drowningDamage: 'true'
      - commandBlockOutput: 'true'
      - forgiveDeadPlayers: 'true'
      - doMobSpawning: 'true'
      - maxEntityCramming: '24'
      - disableRaids: 'false'
      - doWeatherCycle: 'true'
      - doDaylightCycle: 'true'
      - showDeathMessages: 'true'
      - doTileDrops: 'true'
      - universalAnger: 'false'
      - doInsomnia: 'true'
      - doImmediateRespawn: 'false'
      - naturalRegeneration: 'true'
      - doMobLoot: 'true'
      - fallDamage: 'true'
      - keepInventory: 'false'
      - doEntityDrops: 'true'
      - doLimitedCrafting: 'false'
      - mobGriefing: 'true'
      - randomTickSpeed: '3'
      - spawnRadius: '10'
      - doTraderSpawning: 'true'
      - logAdminCommands: 'true'
      - spectatorsGenerateChunks: 'true'
      - sendCommandFeedback: 'true'
      - doPatrolSpawning: 'true'
    - Player:
      - Brain:
        - memories: []
      - HurtByTimestamp: 0
      - SleepTimer: !short "0"
      - Attributes: !list_compound
        - - Base: !double "0.10000000149011612"
          - Name: minecraft:generic.movement_speed
      - Invulnerable: !byte "0"
      - FallFlying: !byte "0"
      - PortalCooldown: 0
      - AbsorptionAmount: 0.0
      - abilities:
        - invulnerable: !byte "0"
        - mayfly: !byte "0"
        - instabuild: !byte "0"
        - walkSpeed: 0.10000000149011612
        - mayBuild: !byte "1"
        - flying: !byte "0"
        - flySpeed: 0.05000000074505806
      - FallDistance: 0.0
      - recipeBook:
        - recipes: !list_end []
        - isBlastingFurnaceFilteringCraftable: !byte "0"
        - isSmokerGuiOpen: !byte "0"
        - isFilteringCraftable: !byte "0"
        - toBeDisplayed: !list_end []
        - isFurnaceGuiOpen: !byte "0"
        - isGuiOpen: !byte "0"
        - isFurnaceFilteringCraftable: !byte "0"
        - isBlastingFurnaceGuiOpen: !byte "0"
        - isSmokerFilteringCraftable: !byte "0"
      - DeathTime: !short "0"
      - XpSeed: 0
      - XpTotal: 0
      - UUID: !int_array
        - -1192605500
        - -1887813040
        - -1272670841
        - -486494335
      - playerGameType: 0
      - seenCredits: !byte "0"
      - Motion: !list_double
        - !double "0.0"
        - !double "-0.0784000015258789"
        - !double "0.0"
      - Health: 20.0
      - foodSaturationLevel: 5.0
      - Air: !short "300"
      - OnGround: !byte "1"
      - Dimension: minecraft:overworld
      - Rotation: !list_float
        - 40.3607177734375
        - 31.37474250793457
      - XpLevel: 0
      - Score: 0
      - Pos: !list_double
        - !double "-89.5"
        - !double "75.0"
        - !double "104.5"
      - previousPlayerGameType: -1
      - Fire: !short "-20"
      - XpP: 0.0
      - EnderItems: !list_end []
      - DataVersion: 2586
      - foodLevel: 20
      - foodExhaustionLevel: 0.0
      - HurtTime: !short "0"
      - SelectedItemSlot: 0
      - Inventory: !list_end []
      - foodTickTimer: 0
    - SpawnY: 73
    - rainTime: 99949
    - thunderTime: 94007
    - SpawnZ: 96
    - hardcore: !byte "0"
    - DifficultyLocked: !byte "0"
    - SpawnX: -96
    - clearWeatherTime: 0
    - thundering: !byte "0"
    - SpawnAngle: 0.0
    - version: 19133
    - BorderSafeZone: !double "5.0"
    - LastPlayed: !long "1612731870523"
    - BorderWarningTime: !double "15.0"
    - ScheduledEvents: !list_end []
    - LevelName: New World
    - BorderSize: !double "60000000.0"
    - DataVersion: 2586
    - DataPacks:
      - Enabled: !list_string
        - vanilla
      - Disabled: !list_end []

```

**Comment by SegzGitHub** [comment]
LMAO! Thank you! I was so used to seeing .gz at the end of log files that I thought that since that was missing it needed -n.
